ALIAS_PASSWORD = "alias_password"
ALIAS = "alias"
PASSWORD = "password"
KEYSTORE = "keystore"
PACKAGE_NAME = "package_name"
REMARK = "remark"
APP_NAME = "app_name"
KEYSTORE_FOLDER = "keystore_folder"
